apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: iot-temperature
  labels:
    app: iot-demo
    strimzi.io/cluster: my-cluster
spec:
  partitions: 10
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: iot-temperature-max
  labels:
    app: iot-demo
    strimzi.io/cluster: my-cluster
spec:
  partitions: 10
  replicas: 3
