apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer2
  namespace: myproject
spec:
  parallelism: 3
  completions: 50
  template:
    spec:
      containers:
      - name: kafka-producer2
        image: confluentinc/cp-kafka:5.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1000Mi"
            cpu: "500m"
        command:
          - sh
          - -c
          - "kafka-producer-perf-test --topic my-topic2 --num-records 2500000 --record-size 5 --throughput 10000000 --producer-props acks=1 buffer.memory=67108864 compression.type=lz4 batch.size=20000 linger.ms=100 retries=0 bootstrap.servers=ip-10-0-133-229.ec2.internal:32122,ip-10-0-133-229.ec2.internal:30200,ip-10-0-133-229.ec2.internal:32511,ip-10-0-133-229.ec2.internal:32497"
      restartPolicy: Never
  backoffLimit: 5
