apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dr
  namespace: argocd
spec:
  # Project description
  description: dr project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: '*'
    server: https://api.ly-demo-dr.openshiftaws.com:6443

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false
