apiVersion: v1
kind: Service
metadata:
  name: {{ .GrafanaServiceName }}
  namespace: {{ .Namespace }}
  annotations:
    {{- range $k, $v := .GrafanaServiceAnnotations }}
    {{ $k }}: {{ $v }}
    {{- end }}
  labels:
    application-monitoring: "true"
    {{- range $k, $v := .GrafanaServiceLabels }}
    {{ $k }}: {{ $v }}
    {{- end }}
spec:
  ports:
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: grafana-http
  selector:
    app: {{ .PodLabelValue }}
  {{- if .GrafanaServiceType }}
  type: {{ .GrafanaServiceType }}
  {{- end }}
