apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .GrafanaIngressName }}
  namespace: {{ .Namespace }}
  annotations:
    {{- range $k, $v := .GrafanaIngressAnnotations }}
    {{ $k }}: {{ $v }}
    {{- end }}
  labels:
    app: {{ .PodLabelValue }}
    {{- range $k, $v := .GrafanaIngressLabels }}
    {{ $k }}: {{ $v }}
    {{- end }}
spec:
  rules:
    - host: {{ .Hostname }}
      http:
        paths:
          - backend:
              serviceName: {{ .GrafanaServiceName }}
              servicePort: 3000
            {{- if .GrafanaIngressPath }}
            path: {{ .GrafanaServiceName }}
            {{- end }}
{{- if .GrafanaIngressTLSEnabled }}
  tls:
  - hosts:
    - {{ .Hostname }}
    secretName: {{ .GrafanaIngressTLSSecretName }}
{{- end }}