apiVersion: v1
data:
  provider.yaml: |-
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      updateIntervalSeconds: 10
      options:
        path: /etc/grafana-dashboards
kind: ConfigMap
metadata:
  name: {{ .GrafanaProvidersConfigMapName }}
  namespace: {{ .Namespace }}
