apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: example-grafana
spec:
  resources:
    requests:
      memory: "250Mi"
      cpu: "100m"
    limits:
      memory: "1000Mi"
      cpu: "500m"
  ingress:
    enabled: True
    hostname: "grafana.apps.127.0.0.1.nip.io"
  config:
    log:
      mode: "console"
      level: "warn"
    security:
      admin_user: "root"
      admin_password: "secret"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.basic:
      enabled: False
    auth.anonymous:
      enabled: False
  dashboardLabelSelector:
    - matchExpressions:
        - {key: app, operator: In, values: [grafana]}
